### ISSUE TITLE
How to pass `area` property using HOC?

### ISSUE THREAD

**Issue by superKalo** [Lemoncode/react-promise-tracker#69]
I'd love to use this lib, but I can't seems to find a way to pass an `area` prop when using the `promiseTrackerHoc` HOC. How I can do that?

**Comment by brauliodiez** [comment]
Hi,

You can feed them using the _config_ props.

```javascript
// Props:
// config: {
//  area:  // can be null|undefined|'' (will default to DefaultArea) or area name
//  delay: // Wait Xms to display the spinner (fast connections scenario avoid blinking)
//            default value 0ms
// }
export const promiseTrackerHoc = ComponentToWrap => {
```

Something like:

```html
<Spinner config={area: 'myarea'}/>
```
I think it would be a good idea to create a new sample for this.

**Comment by brauliodiez** [comment]
Just taking from the unit tests a sample:

```javascript
      // Arrange
      const TestSpinnerComponent = props => <span>test</span>;

      // Act
      const TrackedComponent = promiseTrackerHoc(TestSpinnerComponent);

      // Assert
      const component = mount(
        <TrackedComponent config={{ area: "testArea" }} />
      );
```

**Comment by brauliodiez** [comment]
Just created a codesandbox with the example:

https://codesandbox.io/s/01-example-areas-hoc-ji3fh

Snippets:

Spinner:
```jsx
import React from "react";
import { promiseTrackerHoc } from "react-promise-tracker";
import Loader from "react-loader-spinner";
import "./spinner.css";

const SpinnerInner = (props) =>
    props.promiseInProgress && (
        <div className="spinner">
            <Loader type="ThreeDots" color="#2BAD60" height="100" width="100" />
        </div>
    )

export const Spinner = promiseTrackerHoc(SpinnerInner);
```

Configuring the area (are.post is just a const string):

```jsx
export const PostTable = (props) => (
  <div>
    <Table
      title="Posts"
      items={props.posts}
      headerRender={Header}
      rowRender={Row}
    />
    <Spinner
      config={{area: areas.post}}
    />
  </div>
);
```

**Comment by superKalo** [comment]
Thanks for your quick reply! :)

Okay, I understand now. I wish I could do:

```
higherOrderComponent({ config: { area: 'testArea' } })(MyComponent)
```

Because for my use case, all my spinners are area specific. If loading - do not render the content, but render spinner only. Would be strange to do in my entry point let's say:

```
<Header config={{ area: "header" }} />
<Widget1 config={{ area: "widget1" }} />
<Footer config={{ area: "footer" }} />
```

That's why I'm planning to do one additional HOC placed before the `promiseTrackerHoc`, which will do:

```
export default compose(
    additionalHOC({ config: { area: 'header' } }),
    promiseTrackerHoc,
)(Header);
```

**Comment by brauliodiez** [comment]
I see your point, I think in your case is a good approach to go for the specialized HOC.

About suspense have you take a look at our suspense like examples?

https://codesandbox.io/s/qxw92yjk2w

https://codesandbox.io/s/jm6lzv9q3

Just a curiosity why are you using the HOC implementation instead of the Hooks one?

**Comment by brauliodiez** [comment]
Issue resolved, closing it.

**Comment by superKalo** [comment]
Thanks! We're using HOCs to be consistent with what's been developed so far. The project is ongoing.

I ended up doing this:

```
export const promiseTrackerHocConfig = (config: Config) => (
    WrappedComponent: any,
) => {
    const HOC = (props: any) => {
        return <WrappedComponent {...props} config={config} />;
    };

    return HOC;
};
```

And I'm using it like this:

```
export default compose(
    promiseTrackerHocConfig({ area: 'home-widget' }),
    promiseTrackerHoc,
)(Header);
```

It works, but when I add a `delay` ot 1000 let's say - for some reason the `promiseInProgress` prop in the component goes `false` and then `true` forever. If I remove the `delay` - all good.

Do you maybe have an idea why it breaks?

**Comment by superKalo** [comment]
I don't think that's coming from the HOC, maybe there is an issue with the `delay` prop in general?

**Comment by brauliodiez** [comment]
I will take a look, if it's failing I will open a new issue

**Comment by superKalo** [comment]
Thank you! :)

**Comment by brauliodiez** [comment]
Hi @superKalo,

Reviewing code, I think there maybe an issue on the HOC version will come back to you shortly

Got  a repro here: https://codesandbox.io/s/01-example-areas-hoc-delay-7h59o

@nasdan will release a patch in the following days.

**Comment by nasdan** [comment]
Hi @superKalo, new version [2.0.4](https://github.com/Lemoncode/react-promise-tracker/releases/tag/2.0.4) released with the fix.
Thank you

**Comment by superKalo** [comment]
@Nasdan thank you for releasing the fix! Unfortunately, after I updated, it's still not working.

I'm using the same set-up [I described above](https://github.com/Lemoncode/react-promise-tracker/issues/69#issuecomment-510832472) and I pass the delay like so:

```
export default compose(
    promiseTrackerHocConfig({ area: 'home-widget', delay: 10000 }),
    promiseTrackerHoc,
)(Header);
```

Right now, the `promiseInProgress` prop in the component is okay - it doesn't stay true forever like before. But I don't see any delay. It simply goes `false` as soon as my request arrives.

**Comment by brauliodiez** [comment]
@superKalo "Delay" was build for the following scenario:
  - You got a high speed connection.
  - When you make a request likely it will be completed in miliseconds.
  - You want to avoid a disgusting flickering on your spinner, but you don't want to disable the spinner in case the request takes more than X miliseconds.

The behavior we have implemented:
  - You fire a server request, promise tracker will just wait X milliseconds to notify  the HoC or the Hook, after that X milliseconds it will check if there are promises in progress in that case will trigger the promiseInProgress true.

- Once the request is completed it will substract one to the counter of promises in progress, if it's zero it will just notify the Hoc / Hooks (promiseInProgress false). Here we are always firing this because you don't know how many request you have fired in paralell and how are they behaving, and if promiseInProgress is already falsy it won't impact much.

Maybe we need to add more info about the "delay" behavior.

**Comment by superKalo** [comment]
@brauliodiez , thanks for the detailed explanation. Yes, I understand the motivation for the delay. I need it exactly for dealing with the flickering my loading spinner.

Therefore, setting a 10 seconds delay I would assume the promise tracker will just wait 10 seconds to notify the HoC, correct? That's not happening though.

In a real world scenario I will set it to 1-2seconds the most, of course :-)

**Comment by brauliodiez** [comment]
HoC will wait ten seconds and check if after ten seconds there is any pending promise being track, in that case will send the event indicating that promiseInProgress is true

About the other way around, it will always notify when it goes to falsy.

A sample:

https://codesandbox.io/s/01-example-areas-hoc-delay-7h59o

Click on Load users with delay, it won't show the spinner because we have the following configuration (./src/components/userTable/table.js)

```
    <Spinner
      config={{ area: areas.user, delay:10000}}
    />
```

And the fetch call got 3000 miliseconds delay
```javascript
export const fetchWithDelay = url => {
  const promise = new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(
        fetch(url, {
          method: "GET"
        }).then(response => response.json())
      );
    }, 3000);
  });

  return promise;
};
```

Ten seconds delay behavior:

```javascript
    <Spinner
      config={{ area: areas.user, delay:10000}}
    />
```

![tenseconds](https://user-images.githubusercontent.com/1457912/62447921-c4559100-b766-11e9-94b7-185dd170de9e.gif)

If we set delay to two seconds spinner will be shown (fetch delay is set to 3 seconds)

```javascript
    <Spinner
      config={{ area: areas.user, delay:2000}}
    />
```

![twoseconds](https://user-images.githubusercontent.com/1457912/62448022-04b50f00-b767-11e9-9fee-058afddd7bcb.gif)

Could you please share a codesandbox with the issue, just to be sure I have understood well the problem, thanks.

**Comment by superKalo** [comment]
Sorry for the delay in my response, too many things happening on my side :)

I updated to v2.0.5. Unfortunately, the issue is still present. As far as I understand, when I set a delay of 10 seconds, I would expect to have `promiseInProgress` to be `true` for at least 10 seconds, correct?

What actually happens is that `promiseInProgress` is always `false`. When I remove it - it is working again - goes `true` and then goes `false` when my promise resolves (which resolves very quickly, maybe in about a second).

I use this HOC:

```javascript
export const promiseTrackerHocConfig = (config: Config) => (
    WrappedComponent: any,
) => {
    const HOC = (props: any) => {
        return <WrappedComponent {...props} config={config} />;
    };

    return HOC;
};
```

And I'm using it like this:

```javascript
export default compose(
    promiseTrackerHocConfig({ area: 'widget', delay: 10 * 1000 }),
    promiseTrackerHoc,
)(Header);
```

**Comment by brauliodiez** [comment]
Hi, is the other way around, when you set a Delay of ten seconds it won't show any progress indicator in ten seconds, after than ten seconds it will check if there is any pending promise to be served and it that case it will be displayed.

The use case:

When you have a high speed connection a request may take 100ms to be served, you don't want the loading indicator to be shown just flickering in your screen, but you still want to show it for longer request or for users that have a bad internet connection (e.g. 3G).

**Comment by superKalo** [comment]
@brauliodiez okay, I understand now!

I though it works the other way around - show loading indicator at least for X amount of seconds, because when a request take 100ms to be served, the loading is displayed for at least 2 seconds (let's say). Otherwise - loading indicator flickers for 100ms and the user doesn't understand what's going on. You see?

**Comment by brauliodiez** [comment]
I see your point, the issue there is that you are penalising users that have a fast internet connection, they will have to wait 2 seconds to interact.

If final users have a fast internet connection, then the goal is to avoid flicker and enhance usability (no loading indicator is being shown because is not needed), but if the internet connection is bad and a request takes more than 200Ms to be served then display the loading indicator.

Delay parameter should be 0-500 Ms range, not more (just a minimum amount to avoid show a flickering loading indicator on one hand, but not much to avoid the user interact with a page that is expecting data to be loaded).

Your feedback is quite appreciated we will enhance the documentation for that option to avoid developers to get confused.

**Comment by superKalo** [comment]
I see your point. Thank you, I'm closing the issue then.
